[versions]
agp = "8.10.1"
io-ktor = "3.2.0"
kotlin = "2.1.21"
kotlinxDatetime = "0.6.2"

[libraries]
kotlin-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.8.1"
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "io-ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "io-ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "io-ktor" }
semver = "io.github.z4kn4fein:semver:3.0.0"

[plugins]
androidLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
mavenPublish = "com.vanniktech.maven.publish:0.32.0"
spotless = "com.diffplug.spotless:7.0.4"
versionCatalogUpdate = "nl.littlerobots.version-catalog-update:1.0.0"
